### PR TITLE
Fixes a Crash When a Signature Does Not Align With Itself

### PR DESCRIPTION
**Pull request by emarinier**
This fixes a crash that occurred when a candidate signature was of such poor quality (usually from ambiguous sequence characters such as N, etc.) that BLAST could not align the signature with itself. The software was making an assumption that a candidate signature should always align with itself (aligning the same sequence to itself), but in such cases this assumption isn't true and causes a crash.

### CODE REVIEW

**Review by mattheww95 — APPROVED** [review]
This issue is reminding me of something someone from NCBI told me about another quirk of BLAST that may be worth noting just for awareness as it somewhat relates to this issue. 

Apologies as this explanation is vague as I am writing it from memory, but it is possible for two sequences to have 50% sequence similarity yet for no BLAST match to be recorded depending on the seeds recorded in the database. I can't quite remember all the details however.

Also LGTM 👍

**Review by kylacochrane — APPROVED** [review]
This looks great Eric!

**Review by apetkau — APPROVED** [review]
This looks good to me. Thanks Eric 😄 

Only suggestion I would have is if there's any way to have a test case for this? I realize it might be complex to setup, so it's okay if there is not (and that testing is just something you did on the data causing the crash outside of CI).

**Comment by emarinier** [comment]
> This looks good to me. Thanks Eric 😄
> 
> Only suggestion I would have is if there's any way to have a test case for this? I realize it might be complex to setup, so it's okay if there is not (and that testing is just something you did on the data causing the crash outside of CI).

It might be tricky, but I'll see if I can do something similar to the dataset where I saw this: have the signature sequence have heavy Ns and try to get Neptune to find it while BLAST can't.

**Review by sgsutcliffe — APPROVED** [review]
Looks good - no notes!

**Comment by emarinier** [comment]
> This looks good to me. Thanks Eric 😄
> 
> Only suggestion I would have is if there's any way to have a test case for this? I realize it might be complex to setup, so it's okay if there is not (and that testing is just something you did on the data causing the crash outside of CI).

Add a test case in 5c4c22b.

Unfortunately, the updated CI is in #14, and this test case will likely need to be updated slightly when merging into #14, but I tested that this input causes Neptune to crash on release version 1.2.5 with the same error. It does not crash after the fix. I manually ran pytest for `test_neptune.py` to confirm the test is passing (the other pytest fail because DRMAA-related tests are very much out of date and all of that is fixed in #14).

**Pull request merged**
